/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205730;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarriorTest {

     @Test
     void attackTest() {
    
         int defaultWarriorHp = 100;
         int defaultEnemyHP = 1000;
         for(int i=0; i<3;i++){
         Warrior Warrior = new Warrior("デモ戦士", defaultWarriorHp, 100);
         Enemy enemy = new Enemy("ウェポンくらうスライム", defaultEnemyHP, 0);

         
         Warrior.attackWithWeponSkill(enemy); //overkill
         System.out.println("n");
         
         assertEquals((int)(Warrior.getAttack()*1.5), defaultEnemyHP-enemy.getHitPoint());
         i = i+1; 
        }
     }
 }
